name: My Application Form
fields:
  name:
    "#type": textfield
    "#title": Name
    "#attributes":
      placeholder: "Enter your real name"

  food:
    "#type": checkboxes
    "#title": Food preference
    "#options": ['oriental', 'russian']
    "#default_value": [0]

  body:
    "#type": textarea
    "#title": Resume deluxe super bio

  role:
    "#type": radios
    "#title": Role
    "#options":
      - developer
      - manager
      - ceo
      - tester
      - cleaner
    "#default_value": 2
