<?php
/**
 * @file
 *
 * Example of PSR-4 autoloading.
 *
 * @author itarato
 *
 * @see http://www.php-fig.org/psr/psr-4/
 * @see http://symfony.com/doc/current/components/class_loader/psr4_class_loader.html
 */

// Included namespace for a class of this module.
use MyModule\Acme\Controller\UserController;
use Symfony\Component\ClassLoader\Psr4ClassLoader;

/**
 * Initialize the PSR4 class loader. It makes the classes available for autoloading.
 */
require_once __DIR__ . '/vendor/psr4classloader/Psr4ClassLoader.php';
$loader = new Psr4ClassLoader();

// Register our namespace prefix.
$loader->addPrefix('MyModule\\', __DIR__ . '/src');
$loader->register();

/**
 * Implements hook_menu().
 */
function d7sy_class_loader_menu() {
  return array(
    'd7sy_class_loader' => array(
      'title' => 'Class loader example',
      'access callback' => TRUE,
      'page callback' => 'd7sy_class_loader_page',
    ),
  );
}

function d7sy_class_loader_page() {
  // Use the class now - know that we already loaded the namespace with "use".
  $steve = new UserController("Steve");
  return $steve->__toString();
}
